### ISSUE TITLE
need to add more specific errors to Markdown document

### ISSUE THREAD

**Issue by beanumber** [SmithCollege-SDS/sds-public#5]
For example, if your error says:

```
Error: could not find function "xxx"
```

That probably means that you forgot to load the package that provides function "xxx". Which package is that? Look in the Help

Or, if your error says:

```
Error: object 'xxx' not found
```

that means that R can't find an object called "xxx" in your environment. Is it misspelled? Did you create it in your live R session but not previously define it in your Markdown file?

**Comment by beanumber** [comment]
Should we also share this with the TAs and solicit feedback on common errors that they are seeing?

**Comment by AmeliaMN** [comment]
This is a good idea. There is also 

`Warning: there is no package called 'xxx'`

which means you probably need to 

`install.packages("xxx")`

**Comment by beanumber** [comment]
Yes!
